<template>
    <div>
        <LandingHomeSection/>
        <LandingFeaturesSection/>
        <LandingPrincingSection/>
        <LandingContactSection/>
        <LandingFAQSection/>
    </div>
</template>